import Foundation

public enum NodeShape: String, Codable {
    case box
    case polygon
    case ellipse
    case oval
    case circle
    case point
    case egg
    case triangle
    case plaintext
    case plain
    case diamond
    case trapezium
    case parallelogram
    case house
    case pentagon
    case hexagon
    case septagon
    case octagon
    case doublecircle
    case doubleoctagon
    case tripleoctagon
    case invtriangle
    case invtrapezium
    case invhouse
    case Mdiamond
    case Msquare
    case Mcircle
    case rect
    case rectangle
    case square
    case star
    case none
    case underline
    case cylinder
    case note
    case tab
    case folder
    case box3d
    case component
    case promoter
    case cds
    case terminator
    case utr
    case primersite
    case restrictionsite
    case fivepoverhang
    case threepoverhang
    case noverhang
    case assembly
    case signature
    case insulator
    case ribosite
    case rnastab
    case proteasesite
    case proteinstab
    case rpromoter
    case rarrow
    case larrow
    case lpromoter
}
